apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-backend-env-cm
data:
  frontend_url: {{ .Values.ingress.host }}
  # don't use in production when we have sensitive data
  # only for testing purposes. When sending request from frontend
  # an X-api-key header is added. This is checked against
  # the api_key in the backend to authorize the API operation.
  api_key: "testkey"
  postgres_conn_str: postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Values.argocd.appname }}-postgresql/{{ .Values.postgresql.auth.database }}
  