apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-backend-service
  labels:
    app: {{ .Values.name }}-backend
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
