apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-frontend-service
  labels:
    app: {{ .Values.name }}-frontend
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
