name: kiarva

argocd:
  appname: kiarva

deployment:
  frontendReplicas: 3
  backendReplicas: 3
  container:
    name: kiarva-web-app-prod
    frontendImage: ghcr.io/scilifelabdatacentre/kiarva-frontend:0.0.5
    backendImage: ghcr.io/scilifelabdatacentre/kiarva-backend:0.0.3
    imagePullPolicy: Always

ingress:
  localTest: false
  host: "kiarva-dev.scilifelab-2-prod.sys.kth.se"

np:
  enabled: true
