name: kiarva

argocd:
  appname: kiarva

deployment:
  frontendReplicas: 1
  backendReplicas: 1
  container:
    name: kiarva-web-app-prod
    frontendImage: ghcr.io/scilifelabdatacentre/precision-medicine-portal-frontend:0.3.2
    backendImage: ghcr.io/scilifelabdatacentre/precision-medicine-portal:0.0.2
    imagePullPolicy: Always

ingress:
  localTest: false
  host: "ki-adaptive-immune-receptor-variant-atlas.se"

np:
  enabled: true